## Configuration

### Imports

In [98]:
# Utilities
from IPython.display import display
from fastprogress import master_bar, progress_bar
from datetime import datetime
from unidecode import unidecode
import os
import ntpath
import numpy as np
import statistics 
import re
import math
import random
import datetime
import numbers
from collections.abc import MutableMapping
import pandas as pd
import time
from random import randint
import json

# Botometer API
import botometer

# MongoDB functionality
from pymongo import MongoClient, InsertOne, UpdateOne
from bson import ObjectId

# Concurrency
import concurrent.futures
from tqdm.notebook import tqdm

# Config management
from configparser import ConfigParser


# Directories where CSV data is stored
ROOT_DIR = "/home/mattia/javier/botbusters-spanish-general-elections-network-analysis/"

# Change path to root
os.chdir(ROOT_DIR)

# MongoDB parameters
mongoclient = MongoClient('localhost', 27017)
db = mongoclient.influence

### Support Functions

In [99]:
def flatten(d, parent_key='', sep='_'):
    """Formats MongoDB results
    
    Keyword arguments:
    d -- dictionary with key and uncleaned values
    parent_key --
    sep --
    """
    items = []
    for k, v in d.items():
        new_key = parent_key + sep + k if parent_key else k
        if isinstance(v, MutableMapping):
            items.extend(flatten(v, new_key, sep=sep).items())
        else:
            items.append((new_key, v))
    return dict(items)

def make_objid(text):
    """Makes an ObjectId of 4 bytes
    
    Keyword arguments:
    text -- string to be converted into Object ID
    """
    text = str(text)
    if not text.strip():
        return None
    try:
        return ObjectId(text.rjust(24,"0"))
    except Exception as ex:
        print(text, ex)
        return None


def get_tweets(collection):
    """
    Gets tweets
    
    collection - Tweets MongoDB collection
    """
    tweets = list(collection.find({},
                                 {'_id' : False, 'user_id' : True}))
    
    print("Number of tweets in DB:", len(tweets))
    tweets = [flatten(t) for t in tweets]
    df_tweets = pd.DataFrame(tweets)
    return df_tweets

def get_retweets(collection):
    """
    Gets retweets
    
    collection - Retweets MongoDB collection
    """
    retweets = list(collection.find({},
                                 {'_id': False, 'user_id' : True}))
    
    print("Number of retweets in DB:", len(retweets))
    retweets = [flatten(r) for r in retweets]
    df_retweets = pd.DataFrame(retweets)
    return df_retweets


def get_users(collection):
    """
    Gets users
    
    collection - Users MongoDB collection
    """
    users = list(collection.find({},
                                 {'_id' : True}))
    
    print("Number of users without botscore in DB:", len(users))
    users = [flatten(u) for u in users]
    df_users = pd.DataFrame(users)
    return df_users

## Get number of interactions by user

Get tweets and retweets

In [ ]:
%%time
df_retweets = get_retweets(db.retweets)
display(df_retweets.head(5))

In [7]:
%%time
df_tweets = get_tweets(db.tweets)
display(df_tweets.head(5))

Number of tweets in DB: 1875457

                    user_id
0  000000000000000276977398
1  000000000000002906096735
2  000000000000001620996282
3  000001163542858604916739
4  000000000000000279465279

CPU times: user 8.57 s, sys: 96.1 ms, total: 8.66 s
Wall time: 9.91 s

In [8]:
%%time
freq = df_tweets.user_id.value_counts()
freq2 = df_retweets.user_id.value_counts()
fsum = freq.add(freq2, fill_value=0)
print("Total users:",len(fsum))

Total users: 2802467
CPU times: user 3min 4s, sys: 1.66 s, total: 3min 6s
Wall time: 2min 50s

In [9]:
fsum = fsum.sort_values(ascending=False)
fsum.head(10)

000000000000002479879152    15225.0
000000000000003064247597    11152.0
000000000000003387713985     9829.0
000001061332198266204164     9486.0
000000000000001723241016     8521.0
000000830507792998027266     8233.0
000000000000000216711237     8107.0
000000000000000128534745     7917.0
000000825432095577296896     7845.0
000000000000002420883178     7763.0
Name: user_id, dtype: float64

In [ ]:
operations = []
pos = 0
for user_id, interactions in fsum.items():
    
    try:
        operations.append(UpdateOne({'_id': make_objid(user_id)},
                                    {'$set': { 'num_interactions': int(interactions), 'position_num_interactions': pos }},
                                    upsert=True))  

        if len(operations) >= 100000:
            results = db.users.bulk_write(operations)
            print("M:", str(results.matched_count).rjust(8, " "),
                  " I:", str(results.inserted_count).rjust(8, " "),
                  " U:", str(results.upserted_count).rjust(8, " "))
            operations = []
        
        pos = pos + 1
        
    except Exception as e:
        print("Exception. Message:", e)


if len(operations) > 0: 
    try: 
        results = db.users.bulk_write(operations)
        print("M:", str(results.matched_count).rjust(8, " "),
              " I:", str(results.inserted_count).rjust(8, " "),
              " U:", str(results.upserted_count).rjust(8, " "))
    except Exception as e:
        print("Exception. Message:", e)

## Sampling of 20%

In [3]:
def get_retweets(collection):
    """
    Gets retweets
    
    collection - Retweets MongoDB collection
    """
    retweets = list(collection.find({},
                                 {'_id': True, 'tweet_id' : True, 'user_id' : True}))
    
    print("Number of retweets in DB:", len(retweets))
    retweets = [flatten(r) for r in retweets]
    df_retweets = pd.DataFrame(retweets)
    df_retweets.rename(columns={'user_id':'retweet_author','_id':'retweet_mongo_id'},inplace=True)
    return df_retweets

def get_tweets(collection):
    """
    Gets tweets
    
    collection - Tweets MongoDB collection
    """
    tweets = list(collection.find({},
                                 {'_id' : True, 'user_id' : True, 'tweet_id' : True}))
    
    print("Number of tweets in DB:", len(tweets))
    tweets = [flatten(t) for t in tweets]
    df_tweets = pd.DataFrame(tweets)
    df_tweets.rename(columns={'user_id':'tweet_author', '_id':'tweet_mongo_id'},inplace=True)
    return df_tweets

def get_users(collection):
    """
    Gets users
    
    collection - Users MongoDB collection
    """
    users = list(collection.find({ 'botscore.cap.universal' : { '$exists' : True }},
                                 {'_id' : True, 'botscore.cap.universal' : True})
                 #.limit(LIMIT)
                )
    print("Number of users with botscore in DB:", len(users))
    users = [flatten(u) for u in users]
    df_users = pd.DataFrame(users)
    return df_users

In [9]:
%%time
df_retweets = get_retweets(db.retweets)
display(df_retweets.head(5))

Number of retweets in DB: 39344305

,retweet_mongo_id,tweet_id,retweet_author
0,000001193668589628383234,000001193667913368121351,000000000000004460826197
1,000001192582587753140230,000001192581634291355649,000001075150211725619200
2,000001185317085502738433,000001185312751301906433,000000000000003251522811
3,000001190660503070236672,000001190659978471911424,000000000000000904385876
4,000001190660746096644099,000001190659978471911424,000000952575694021758976

CPU times: user 8min 48s, sys: 34.3 s, total: 9min 22s
Wall time: 9min 46s

In [10]:
%%time
df_tweets = get_tweets(db.tweets)
display(df_tweets.head(5))

Number of tweets in DB: 1875457

,tweet_mongo_id,tweet_author,tweet_id
0,a86e778c-46a3-11ea-9505-02420a0000af,000000000000000276977398,000001191462058602192907
1,44a195f2-468c-11ea-9505-02420a0000af,000000000000002906096735,000001191481739606183937
2,44a1996c-468c-11ea-9505-02420a0000af,000000000000001620996282,000001191488966639443968
3,75dba318-46a7-11ea-9505-02420a0000af,000001163542858604916739,000001191464452987772928
4,77c4e81a-46a7-11ea-9505-02420a0000af,000000000000000279465279,000001191464087064109058

CPU times: user 19.8 s, sys: 398 ms, total: 20.2 s
Wall time: 21.6 s

In [11]:
%%time
users = get_users(db.users)
display(users.head(5))

In [16]:
set_calculated_users = set(users._id)

#### Tag sampled data

In [82]:
df_sample = df_retweets.sample(frac=0.2, random_state=30100)
print("Number of interactions in the sample:", len(df_sample))

Number of interactions in the sample: 7868861

In [83]:
df_sample = df_sample.set_index('tweet_id').join(df_tweets.set_index('tweet_id')).reset_index(drop=True)
df_sample.head(5)

,retweet_mongo_id,retweet_author,tweet_mongo_id,tweet_author
0,000001188606157725847552,000000722509814165827585,c75e7c0a-4671-11ea-a6d9-02420a000681,000000000000000068740712
1,000001191543404716580864,000000000000000595890179,c75e7c0a-4671-11ea-a6d9-02420a000681,000000000000000068740712
2,000001174059596966748160,000000000000000468655723,c75e7c0a-4671-11ea-a6d9-02420a000681,000000000000000068740712
3,000001174076516826865664,000000000000000008576412,c75e7c0a-4671-11ea-a6d9-02420a000681,000000000000000068740712
4,000001227330608566820864,000000000000000232342510,c75e7c0a-4671-11ea-a6d9-02420a000681,000000000000000068740712

In [84]:
set_users = set(df_sample.retweet_author.unique()) 
set_users = set_users.union(set(df_sample.tweet_author.unique()))
print("Number of users involved in sample:", len(set_users))

Number of users involved in sample: 1297975

In [85]:
df_sample.head()

,retweet_mongo_id,retweet_author,tweet_mongo_id,tweet_author
0,000001188606157725847552,000000722509814165827585,c75e7c0a-4671-11ea-a6d9-02420a000681,000000000000000068740712
1,000001191543404716580864,000000000000000595890179,c75e7c0a-4671-11ea-a6d9-02420a000681,000000000000000068740712
2,000001174059596966748160,000000000000000468655723,c75e7c0a-4671-11ea-a6d9-02420a000681,000000000000000068740712
3,000001174076516826865664,000000000000000008576412,c75e7c0a-4671-11ea-a6d9-02420a000681,000000000000000068740712
4,000001227330608566820864,000000000000000232342510,c75e7c0a-4671-11ea-a6d9-02420a000681,000000000000000068740712

In [87]:
%%time 

collections = {
    'retweet_mongo_id' : db.retweets,
    'retweet_author' : db.users,
    'tweet_mongo_id' : db.tweets,
    'tweet_author': db.users
}

for column in ['retweet_mongo_id','retweet_author','tweet_mongo_id','tweet_author']:
    
    num_entries = len(df_sample[column])
    operations = []
    collection = collections[column]
    print(column)
    
    for row in range(0,num_entries):
        _id = df_sample[column][row]
        try:
            operations.append(UpdateOne({'_id': _id},
                                        {'$set': { 'sampled': True}},
                                        upsert=True))
            
            if len(operations) >= 1000000:
                results = collection.bulk_write(operations)
                print("M:", str(results.matched_count).rjust(8, " "),
                      " I:", str(results.inserted_count).rjust(8, " "),
                      " U:", str(results.upserted_count).rjust(8, " "))
                operations = []
                
        except Exception as e:
            print("Exception. Message:", e)

    if len(operations) > 0: 
        try: 
            results = collection.bulk_write(operations)
            print("M:", str(results.matched_count).rjust(8, " "),
                  " I:", str(results.inserted_count).rjust(8, " "),
                  " U:", str(results.upserted_count).rjust(8, " "))
        except Exception as e:
            print("Exception. Message:", e)

retweet_mongo_id
M:  1000000  I:        0  U:        0
M:  1000000  I:        0  U:        0
M:  1000000  I:        0  U:        0
M:  1000000  I:        0  U:        0
M:  1000000  I:        0  U:        0
M:  1000000  I:        0  U:        0
M:  1000000  I:        0  U:        0
M:   868861  I:        0  U:        0
retweet_author
M:  1000000  I:        0  U:        0
M:  1000000  I:        0  U:        0
M:  1000000  I:        0  U:        0
M:  1000000  I:        0  U:        0
M:  1000000  I:        0  U:        0
M:  1000000  I:        0  U:        0
M:  1000000  I:        0  U:        0
M:   868861  I:        0  U:        0
tweet_mongo_id
M:  1000000  I:        0  U:        0
M:  1000000  I:        0  U:        0
M:  1000000  I:        0  U:        0
M:  1000000  I:        0  U:        0
M:  1000000  I:        0  U:        0
M:  1000000  I:        0  U:        0
M:  1000000  I:        0  U:        0
M:   868861  I:        0  U:        0
tweet_author
M:  1000000  I:        0  U:        0
M:  1000000  I:        0  U:        0
M:  1000000  I:        0  U:        0
M:  1000000  I:        0  U:        0
M:  1000000  I:        0  U:        0
M:  1000000  I:        0  U:        0
M:  1000000  I:        0  U:        0
M:   868861  I:        0  U:        0
CPU times: user 29min 5s, sys: 2.3 s, total: 29min 7s
Wall time: 46min 24s

## Get Botscores

In [101]:
def get_users_for_botscore(collection):
    """
    Gets users
    
    collection - Users MongoDB collection
    """
    users = list(collection.find({ '$and' : [ { 'sampled': True } , { 'botscore' : { '$exists' : False } }]},
                                 {'_id' : True, 'num_interactions' : True}))
    
    print("Number of sampled users without botscore in DB:", len(users))
    users = [flatten(u) for u in users]
    df_users = pd.DataFrame(users)
    return df_users

Get users without botscore

In [102]:
%%time
config_object = ConfigParser()
config_object.read("config.init")
botometer_instance = botometer.BotometerLite(wait_on_ratelimit=True,
                          rapidapi_key=config_object.get('key','rapidapi_key'),
                          **{'consumer_key':config_object.get('key','consumer_key'),
                         'consumer_secret':config_object.get('key','consumer_secret')})

CPU times: user 16.2 ms, sys: 0 ns, total: 16.2 ms
Wall time: 385 ms

Order by importance

Request botscore by importance and respecting daily quota

In [105]:
### CHECKKK
daily_limit = 396 ### CHECKKK
### CHECKKK

today = str(pd.to_datetime(pd.to_datetime('today').strftime(format='%Y-%m-%d')))[0:10]
df_users = get_users_for_botscore(db.users)
df_users = df_users.sort_values(by='num_interactions', axis='index', ascending=False)

for request in progress_bar(range(0, daily_limit)):
    
    print("Request "+str(request)+" ...")
    
    start = request*100
    end = start+100
 
    user_list = df_users[start:end]['_id'].astype(str).astype(int).tolist()
        
    try:    
        results = botometer_instance.check_accounts_from_user_ids(user_list)
        
        print("Results received: ", len(results))
        
        with open(ROOT_DIR+f"botscores/results-{today}.log", 'a') as output_file:
            for res in results:
                json.dump(res, output_file) 
                output_file.write("\n")
                

        if len(results) < 100:
            result_user_ids = []
            for result_user in results:
                result_user_id = result_user.get("user_id")
                result_user_ids.append(result_user_id)
            
            for requested_user in user_list:
                if requested_user not in result_user_ids:
                    r = db.users.update_one({'_id': make_objid(str(requested_user))},
                                           {'$set': { 'botscore' : -3, 'reason':'not found'}},
                                            upsert=True)

        for result in results:
            user_id = make_objid(str(result.get('user_id')))
            botscore = result.get('botscore', False)
            
            if botscore is False:
                error = result.get('error')
                r = db.users.update_one({'_id': user_id},
                                           {'$set': { 'botscore' : -3, 'reason': str(error)}},
                                            upsert=True)     
            else:
                r = db.users.update_one({'_id': user_id},
                                           {'$set': { 'botscore' : botscore}, 
                                            '$unset': {'reason':''}},
                                            upsert=True)        
    
    except Exception as e:
        error = str(request) + " request -> Exception; Message: " + str(e) + "\n"
        myfile = open(ROOT_DIR+"error.log", 'a')
        myfile.write(error)
        myfile.close()
        raise

    
    time.sleep(2)

df_users = get_users_for_botscore(db.users)

Number of sampled users without botscore in DB: 39561

Request 0 ...
Results received:  98
Request 1 ...
Results received:  99
Request 2 ...
Results received:  96
Request 3 ...
Results received:  99
Request 4 ...
Results received:  97
Request 5 ...
Results received:  93
Request 6 ...
Results received:  98
Request 7 ...
Results received:  99
Request 8 ...
Results received:  100
Request 9 ...
Results received:  98
Request 10 ...
Results received:  98
Request 11 ...
Results received:  97
Request 12 ...
Results received:  99
Request 13 ...
Results received:  99
Request 14 ...
Results received:  98
Request 15 ...
Results received:  99
Request 16 ...
Results received:  97
Request 17 ...
Results received:  100
Request 18 ...
Results received:  97
Request 19 ...
Results received:  97
Request 20 ...
Results received:  98
Request 21 ...
Results received:  99
Request 22 ...
Results received:  95
Request 23 ...
Results received:  98
Request 24 ...
Results received:  97
Request 25 ...
Results received:  97
Request 26 ...
Results received:  99
Request 27 ...
Results received:  96
Request 28 ...
Results received:  98
Request 29 ...
Results received:  100
Request 30 ...
Results received:  97
Request 31 ...
Results received:  97
Request 32 ...
Results received:  99
Request 33 ...
Results received:  100
Request 34 ...
Results received:  100
Request 35 ...
Results received:  100
Request 36 ...
Results received:  98
Request 37 ...
Results received:  99
Request 38 ...
Results received:  100
Request 39 ...
Results received:  98
Request 40 ...
Results received:  98
Request 41 ...
Results received:  99
Request 42 ...
Results received:  98
Request 43 ...
Results received:  98
Request 44 ...
Results received:  99
Request 45 ...
Results received:  97
Request 46 ...
Results received:  99
Request 47 ...
Results received:  96
Request 48 ...
Results received:  98
Request 49 ...
Results received:  99
Request 50 ...
Results received:  98
Request 51 ...
Results received:  99
Request 52 ...
Results received:  97
Request 53 ...
Results received:  97
Request 54 ...
Results received:  100
Request 55 ...
Results received:  95
Request 56 ...
Results received:  97
Request 57 ...
Results received:  97
Request 58 ...
Results received:  96
Request 59 ...
Results received:  99
Request 60 ...
Results received:  99
Request 61 ...
Results received:  96
Request 62 ...
Results received:  100
Request 63 ...
Results received:  99
Request 64 ...
Results received:  99
Request 65 ...
Results received:  98
Request 66 ...
Results received:  100
Request 67 ...
Results received:  98
Request 68 ...
Results received:  99
Request 69 ...
Results received:  99
Request 70 ...
Results received:  99
Request 71 ...
Results received:  94
Request 72 ...
Results received:  99
Request 73 ...
Results received:  97
Request 74 ...
Results received:  99
Request 75 ...
Results received:  98
Request 76 ...
Results received:  99
Request 77 ...
Results received:  99
Request 78 ...
Results received:  95
Request 79 ...
Results received:  99
Request 80 ...
Results received:  99
Request 81 ...
Results received:  96
Request 82 ...
Results received:  97
Request 83 ...
Results received:  96
Request 84 ...
Results received:  96
Request 85 ...
Results received:  95
Request 86 ...
Results received:  97
Request 87 ...
Results received:  99
Request 88 ...
Results received:  98
Request 89 ...
Results received:  100
Request 90 ...
Results received:  100
Request 91 ...
Results received:  97
Request 92 ...
Results received:  100
Request 93 ...
Results received:  96
Request 94 ...
Results received:  98
Request 95 ...
Results received:  96
Request 96 ...
Results received:  98
Request 97 ...
Results received:  98
Request 98 ...
Results received:  96
Request 99 ...
Results received:  98
Request 100 ...
Results received:  99
Request 101 ...
Results received:  97
Request 102 ...
Results received:  100
Request 103 ...
Results received:  99
Request 104 ...
Results received:  99
Request 105 ...
Results received:  98
Request 106 ...
Results received:  98
Request 107 ...
Results received:  99
Request 108 ...
Results received:  97
Request 109 ...
Results received:  97
Request 110 ...
Results received:  98
Request 111 ...
Results received:  99
Request 112 ...
Results received:  97
Request 113 ...
Results received:  96
Request 114 ...
Results received:  99
Request 115 ...
Results received:  98
Request 116 ...
Results received:  98
Request 117 ...
Results received:  99
Request 118 ...
Results received:  94
Request 119 ...
Results received:  97
Request 120 ...
Results received:  99
Request 121 ...
Results received:  95
Request 122 ...
Results received:  100
Request 123 ...
Results received:  96
Request 124 ...
Results received:  98
Request 125 ...
Results received:  99
Request 126 ...
Results received:  99
Request 127 ...
Results received:  98
Request 128 ...
Results received:  99
Request 129 ...
Results received:  100
Request 130 ...
Results received:  97
Request 131 ...
Results received:  95
Request 132 ...
Results received:  96
Request 133 ...
Results received:  98
Request 134 ...
Results received:  97
Request 135 ...
Results received:  100
Request 136 ...
Results received:  98
Request 137 ...
Results received:  99
Request 138 ...
Results received:  99
Request 139 ...
Results received:  96
Request 140 ...
Results received:  98
Request 141 ...
Results received:  100
Request 142 ...
Results received:  99
Request 143 ...
Results received:  99
Request 144 ...
Results received:  95
Request 145 ...
Results received:  97
Request 146 ...
Results received:  97
Request 147 ...
Results received:  99
Request 148 ...
Results received:  98
Request 149 ...
Results received:  99
Request 150 ...
Results received:  98
Request 151 ...
Results received:  97
Request 152 ...
Results received:  99
Request 153 ...
Results received:  99
Request 154 ...
Results received:  97
Request 155 ...
Results received:  96
Request 156 ...
Results received:  99
Request 157 ...
Results received:  99
Request 158 ...
Results received:  99
Request 159 ...
Results received:  100
Request 160 ...
Results received:  99
Request 161 ...
Results received:  98
Request 162 ...
Results received:  97
Request 163 ...
Results received:  98
Request 164 ...
Results received:  99
Request 165 ...
Results received:  100
Request 166 ...
Results received:  96
Request 167 ...
Results received:  97
Request 168 ...
Results received:  97
Request 169 ...
Results received:  99
Request 170 ...
Results received:  98
Request 171 ...
Results received:  95
Request 172 ...
Results received:  97
Request 173 ...
Results received:  100
Request 174 ...
Results received:  97
Request 175 ...
Results received:  98
Request 176 ...
Results received:  98
Request 177 ...
Results received:  99
Request 178 ...
Results received:  100
Request 179 ...
Results received:  99
Request 180 ...
Results received:  97
Request 181 ...
Results received:  99
Request 182 ...
Results received:  97
Request 183 ...
Results received:  98
Request 184 ...
Results received:  97
Request 185 ...
Results received:  99
Request 186 ...
Results received:  99
Request 187 ...
Results received:  98
Request 188 ...
Results received:  100
Request 189 ...
Results received:  99
Request 190 ...
Results received:  99
Request 191 ...
Results received:  98
Request 192 ...
Results received:  100
Request 193 ...
Results received:  98
Request 194 ...
Results received:  97
Request 195 ...
Results received:  100
Request 196 ...
Results received:  98
Request 197 ...
Results received:  99
Request 198 ...
Results received:  98
Request 199 ...
Results received:  98
Request 200 ...
Results received:  100
Request 201 ...
Results received:  97
Request 202 ...
Results received:  99
Request 203 ...
Results received:  98
Request 204 ...
Results received:  96
Request 205 ...
Results received:  94
Request 206 ...
Results received:  98
Request 207 ...
Results received:  97
Request 208 ...
Results received:  98
Request 209 ...
Results received:  98
Request 210 ...
Results received:  100
Request 211 ...
Results received:  100
Request 212 ...
Results received:  98
Request 213 ...
Results received:  98
Request 214 ...
Results received:  99
Request 215 ...
Results received:  98
Request 216 ...
Results received:  99
Request 217 ...
Results received:  97
Request 218 ...
Results received:  99
Request 219 ...
Results received:  99
Request 220 ...
Results received:  97
Request 221 ...
Results received:  96
Request 222 ...
Results received:  99
Request 223 ...
Results received:  100
Request 224 ...
Results received:  98
Request 225 ...
Results received:  99
Request 226 ...
Results received:  96
Request 227 ...
Results received:  97
Request 228 ...
Results received:  97
Request 229 ...
Results received:  99
Request 230 ...
Results received:  96
Request 231 ...
Results received:  99
Request 232 ...
Results received:  97
Request 233 ...
Results received:  99
Request 234 ...
Results received:  99
Request 235 ...
Results received:  100
Request 236 ...
Results received:  100
Request 237 ...
Results received:  100
Request 238 ...
Results received:  99
Request 239 ...
Results received:  100
Request 240 ...
Results received:  97
Request 241 ...
Results received:  97
Request 242 ...
Results received:  100
Request 243 ...
Results received:  99
Request 244 ...
Results received:  98
Request 245 ...
Results received:  100
Request 246 ...
Results received:  100
Request 247 ...
Results received:  99
Request 248 ...
Results received:  98
Request 249 ...
Results received:  99
Request 250 ...
Results received:  100
Request 251 ...
Results received:  98
Request 252 ...
Results received:  99
Request 253 ...
Results received:  98
Request 254 ...
Results received:  97
Request 255 ...
Results received:  98
Request 256 ...
Results received:  99
Request 257 ...
Results received:  96
Request 258 ...
Results received:  97
Request 259 ...
Results received:  98
Request 260 ...
Results received:  99
Request 261 ...
Results received:  97
Request 262 ...
Results received:  98
Request 263 ...
Results received:  100
Request 264 ...
Results received:  99
Request 265 ...
Results received:  100
Request 266 ...
Results received:  99
Request 267 ...
Results received:  100
Request 268 ...
Results received:  98
Request 269 ...
Results received:  98
Request 270 ...
Results received:  99
Request 271 ...
Results received:  100
Request 272 ...
Results received:  97
Request 273 ...
Results received:  98
Request 274 ...
Results received:  100
Request 275 ...
Results received:  98
Request 276 ...
Results received:  95
Request 277 ...
Results received:  98
Request 278 ...
Results received:  94
Request 279 ...
Results received:  99
Request 280 ...
Results received:  100
Request 281 ...
Results received:  98
Request 282 ...
Results received:  98
Request 283 ...
Results received:  97
Request 284 ...
Results received:  99
Request 285 ...
Results received:  99
Request 286 ...
Results received:  99
Request 287 ...
Results received:  100
Request 288 ...
Results received:  100
Request 289 ...
Results received:  99
Request 290 ...
Results received:  99
Request 291 ...
Results received:  99
Request 292 ...
Results received:  98
Request 293 ...
Results received:  98
Request 294 ...
Results received:  99
Request 295 ...
Results received:  99
Request 296 ...
Results received:  96
Request 297 ...
Results received:  99
Request 298 ...
Results received:  99
Request 299 ...
Results received:  100
Request 300 ...
Results received:  96
Request 301 ...
Results received:  99
Request 302 ...
Results received:  99
Request 303 ...
Results received:  100
Request 304 ...
Results received:  99
Request 305 ...
Results received:  98
Request 306 ...
Results received:  99
Request 307 ...
Results received:  96
Request 308 ...
Results received:  98
Request 309 ...
Results received:  99
Request 310 ...
Results received:  96
Request 311 ...
Results received:  99
Request 312 ...
Results received:  96
Request 313 ...
Results received:  97
Request 314 ...
Results received:  99
Request 315 ...
Results received:  99
Request 316 ...
Results received:  100
Request 317 ...
Results received:  97
Request 318 ...
Results received:  100
Request 319 ...
Results received:  98
Request 320 ...
Results received:  98
Request 321 ...
Results received:  93
Request 322 ...
Results received:  99
Request 323 ...
Results received:  100
Request 324 ...
Results received:  100
Request 325 ...
Results received:  98
Request 326 ...
Results received:  100
Request 327 ...
Results received:  98
Request 328 ...
Results received:  99
Request 329 ...
Results received:  100
Request 330 ...
Results received:  100
Request 331 ...
Results received:  99
Request 332 ...
Results received:  99
Request 333 ...
Results received:  98
Request 334 ...
Results received:  99
Request 335 ...
Results received:  100
Request 336 ...
Results received:  100
Request 337 ...
Results received:  97
Request 338 ...
Results received:  98
Request 339 ...
Results received:  100
Request 340 ...
Results received:  97
Request 341 ...
Results received:  95
Request 342 ...
Results received:  100
Request 343 ...
Results received:  98
Request 344 ...
Results received:  97
Request 345 ...
Results received:  97
Request 346 ...
Results received:  98
Request 347 ...
Results received:  97
Request 348 ...
Results received:  99
Request 349 ...
Results received:  98
Request 350 ...
Results received:  100
Request 351 ...
Results received:  99
Request 352 ...
Results received:  96
Request 353 ...
Results received:  98
Request 354 ...
Results received:  97
Request 355 ...
Results received:  98
Request 356 ...
Results received:  99
Request 357 ...
Results received:  98
Request 358 ...
Results received:  96
Request 359 ...
Results received:  99
Request 360 ...
Results received:  98
Request 361 ...
Results received:  99
Request 362 ...
Results received:  95
Request 363 ...
Results received:  98
Request 364 ...
Results received:  97
Request 365 ...
Results received:  98
Request 366 ...
Results received:  98
Request 367 ...
Results received:  99
Request 368 ...
Results received:  99
Request 369 ...
Results received:  96
Request 370 ...
Results received:  100
Request 371 ...
Results received:  97
Request 372 ...
Results received:  97
Request 373 ...
Results received:  100
Request 374 ...
Results received:  98
Request 375 ...
Results received:  99
Request 376 ...
Results received:  97
Request 377 ...
Results received:  100
Request 378 ...
Results received:  99
Request 379 ...
Results received:  99
Request 380 ...
Results received:  97
Request 381 ...
Results received:  98
Request 382 ...
Results received:  99
Request 383 ...
Results received:  98
Request 384 ...
Results received:  100
Request 385 ...
Results received:  98
Request 386 ...
Results received:  97
Request 387 ...
Results received:  99
Request 388 ...
Results received:  100
Request 389 ...
Results received:  97
Request 390 ...
Results received:  98
Request 391 ...
Results received:  99
Request 392 ...
Results received:  99
Request 393 ...
Results received:  95
Request 394 ...
Results received:  96
Request 395 ...
Results received:  61
Number of sampled users without botscore in DB: 0

## Checkings

In [60]:
df_users = get_users_for_botscore(db.users)

Number of sampled users without botscore in DB: 1159461
1159461

In [ ]:
%%time 

today = str(pd.to_datetime(pd.to_datetime('today').strftime(format='%Y-%m-%d')))[0:10]

with open(f"botscores/results-{today}.log") as f:
    for line in f:
        result = json.loads(line) 
        botscore, user_id = result.get('botscore'), result.get('user_id')
        print(line, "jj")

In [ ]:
data = []
with open('file') as f:
    for line in f:
        data.append(json.loads(line))